/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DeviceAdapterOptions {
  bleUuid?: string
  rssiIntervalMs?: number
  /** If present, this will record the XDF to this path */
  xdfRecordPath?: string
}
export declare class MuseDevice {
  constructor(options: DeviceAdapterOptions)
  connect(): Promise<void>
  startStreaming(): Promise<void>
  stopStreaming(): Promise<void>
  disconnect(): Promise<void>
  /** @throws if its not connected */
  get bleName(): string
  /** @throws if its not connected */
  get bleUuid(): string
  get isStreaming(): boolean
  get isConnected(): boolean
}
