/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface StreamOptions {
  
}
export declare class MuseDevice {
  constructor()
  connect(): Promise<void>
  startStreaming(options: StreamOptions): Promise<void>
  stopStreaming(): Promise<void>
}
